const PIPELINE_STAGES = ['ONBOARDING', 'DUE_DILIGENCE', 'IC_APPROVAL', 'DISBURSEMENT', 'PORTFOLIO_MONITORING'];
const SECTORS = ['SOLAR', 'MINI_GRID', 'EV_MOBILITY', 'BATTERY_STORAGE', 'OTHER'];
const INTEGRATION_TYPES = ['API', 'MANUAL', 'HYBRID'];
const DREEF_STAGES = ['NOT_STARTED', 'INITIAL_ASSESSMENT', 'MANDATED', 'UNDER_GUARANTEE', 'DISBURSED', 'NOT_APPLICABLE'];
const GUARANTEE_TYPES = ['CREDIT_GUARANTEE', 'CFBF_CO_FINANCE', 'BOTH', 'NONE'];
const CUSTOMER_STATUSES = ['PIPELINE', 'ASSET_ORDERED', 'INSTALLATION_SCHEDULED', 'ACTIVE', 'IN_ARREARS', 'DEFAULTED', 'CHURNED'];
const PIPELINE_CUSTOMER_STATUSES = ['PIPELINE', 'ASSET_ORDERED', 'INSTALLATION_SCHEDULED'];
const CUSTOMER_SEGMENTS = ['RESIDENTIAL', 'SME', 'COMMERCIAL', 'COMMUNITY', 'INSTITUTION'];

module.exports = {
  PIPELINE_STAGES,
  SECTORS,
  INTEGRATION_TYPES,
  DREEF_STAGES,
  GUARANTEE_TYPES,
  CUSTOMER_STATUSES,
  PIPELINE_CUSTOMER_STATUSES,
  CUSTOMER_SEGMENTS,
};
