const PIPELINE_STAGES = ['ONBOARDING', 'DUE_DILIGENCE', 'IC_APPROVAL', 'DISBURSEMENT', 'PORTFOLIO_MONITORING'];
const SECTORS = ['SOLAR', 'MINI_GRID', 'EV_MOBILITY', 'BATTERY_STORAGE', 'OTHER'];
const INTEGRATION_TYPES = ['API', 'MANUAL', 'HYBRID'];

module.exports = { PIPELINE_STAGES, SECTORS, INTEGRATION_TYPES };
