const PIPELINE_STAGES = ['ONBOARDING', 'DUE_DILIGENCE', 'IC_APPROVAL', 'DISBURSEMENT', 'PORTFOLIO_MONITORING'];
const SECTORS = ['SOLAR', 'MINI_GRID', 'EV_MOBILITY', 'BATTERY_STORAGE', 'OTHER'];
const INTEGRATION_TYPES = ['API', 'MANUAL', 'HYBRID'];
const DREEF_STAGES = ['NOT_STARTED', 'INITIAL_ASSESSMENT', 'MANDATED', 'UNDER_GUARANTEE', 'DISBURSED', 'NOT_APPLICABLE'];
const GUARANTEE_TYPES = ['CREDIT_GUARANTEE', 'CFBF_CO_FINANCE', 'BOTH', 'NONE'];

module.exports = { PIPELINE_STAGES, SECTORS, INTEGRATION_TYPES, DREEF_STAGES, GUARANTEE_TYPES };
