const FACILITY_TYPES = ['LOAN', 'EQUITY', 'CONVERTIBLE_NOTE', 'GRANT', 'BLENDED'];
const REPAYMENT_FREQUENCIES = ['MONTHLY', 'QUARTERLY', 'SEMI_ANNUAL', 'ANNUAL', 'BULLET', 'FLEXIBLE'];
const FACILITY_STATUSES = ['ACTIVE', 'FULLY_REPAID', 'IN_ARREARS', 'IN_DEFAULT', 'RESTRUCTURED', 'WRITTEN_OFF'];
const PAYMENT_TYPES = ['SCHEDULED', 'EARLY_REPAYMENT', 'PARTIAL', 'RESTRUCTURED_PAYMENT'];
const SCHEDULE_STATUSES = ['PENDING', 'PAID', 'PARTIALLY_PAID', 'MISSED', 'WAIVED'];
const MILESTONE_STATUSES = ['PENDING', 'IN_PROGRESS', 'COMPLETED', 'DELAYED'];

const MONTHS_PER_PERIOD = { MONTHLY: 1, QUARTERLY: 3, SEMI_ANNUAL: 6, ANNUAL: 12 };

module.exports = {
  FACILITY_TYPES,
  REPAYMENT_FREQUENCIES,
  FACILITY_STATUSES,
  PAYMENT_TYPES,
  SCHEDULE_STATUSES,
  MILESTONE_STATUSES,
  MONTHS_PER_PERIOD,
};
